import json
import os
import time
import zipfile

os.chdir('src/main/resources/assets/tfc_decoration/')

ROCK_TYPES = [
    'granite',
    'diorite',
    'gabbro',
    'shale',
    'claystone',
    'rocksalt',
    'limestone',
    'conglomerate',
    'dolomite',
    'chert',
    'chalk',
    'rhyolite',
    'basalt',
    'andesite',
    'dacite',
    'quartzite',
    'slate',
    'phyllite',
    'schist',
    'gneiss',
    'marble',
	'blaimorite',
    'boninite',
    'carbonatite',
    'foidolite',
    'arkose',
    'jaspillite',
    'travertine',
    'wackestone',
    'blueschist',
    'greenschist',
    'cataclasite',
    'mylonite'
]

FULLBLOCK_TYPES = [
    'mossy_cobble',
	'mossy_bricks',
	'cracked_bricks',
	'mud_bricks',
    'sandstone',
    'mud_pillar',
    'pillar',
    'sandstone_pillar',
    'raw_mud'
]

WOOD_TYPES = [
    'ash',
    'aspen',
    'birch',
    'chestnut',
    'douglas_fir',
    'hickory',
    'maple',
    'oak',
    'pine',
    'sequoia',
    'spruce',
    'sycamore',
    'white_cedar',
    'willow',
    'kapok',
    'acacia',
    'rosewood',
    'blackwood',
    'palm',
    'hevea'
]

def del_none(d):
    """
    https://stackoverflow.com/a/4256027/4355781
    Modifies input!
    """
    for key, value in list(d.items()):
        if value is None:
            del d[key]
        elif isinstance(value, dict):
            del_none(value)
    return d


def blockstate(filename_parts, model, textures, variants=None, uvlock=None):
    """
    Magic.
    :param filename_parts: Iterable of strings.
    :param model: String or None
    :param textures: Dict of <string>:<string> OR <iterable of strings>:<string>
    :param variants: Dict of <string>:<variant> OR "normal":None (to disable the normal default)
    """
    _variants = {
        'normal': [{}]
    }
    if variants:
        _variants.update(variants)

    # Unpack any tuple keys to simple string->string pairs
    _textures = {}
    for key, val in textures.items():
        if isinstance(key, str):
            _textures[key] = val
        else:
            for x in key:
                _textures[x] = val

    p = os.path.join('blockstates', *filename_parts) + '.json'
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as file:
        json.dump(del_none({
            '__comment': 'Generated by generateResources.py function: blockstate',
            'forge_marker': 1,
            'defaults': {
                'model': model,
                'textures': _textures,
                'uvlock': True if uvlock else None
            },
            'variants': _variants
        }), file, indent=2)


def cube_all(filename_parts, texture, variants=None, model='cube_all'):
    blockstate(filename_parts, model, textures={'all': texture}, variants=variants)
def cube_bottom_top(filename_parts, texture, variants=None, model='cube_bottom_top'):
    blockstate(filename_parts, model, textures={'side': texture[0], 'bottom': texture[1], 'top': texture[2]}, variants=variants)
def cube_column(filename_parts, texture, variants=None, model='cube_column') :
    blockstate(filename_parts, model, textures={'side': texture[0], 'end': texture[1]}, variants=variants)

def model(filename_parts, parent, textures):
    p = os.path.join('models', *filename_parts) + '.json'
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as file:
        json.dump(del_none({
            '__comment': 'Generated by generateResources.py function: model',
            'parent': parent,
            'textures': textures,
        }), file, indent=2)


def item(filename_parts, *layers, parent='item/generated'):
    model(('item', *filename_parts), parent,
          None if len(layers) == 0 else {'layer%d' % i: v for i, v in enumerate(layers)})

def shapedRecipe(filename_parts, wood):
    p = os.path.join('..\\tfc_decoration/recipes', *filename_parts) + '.json'
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as file:
        json.dump(del_none({
            "type": "minecraft:crafting_shaped",
              "pattern": [
                "XBX",
                "XBX"
              ],
              "key": {
                "X": {
                  "item": "tfc:wood/log/"+wood
                },
                "B": {
                  "item": "tfc:wood/lumber/"+wood
                }
              },
              "result": {
                "item": 'tfc_decoration:wood/fence_log/'+wood,
                "count": 8
              }
        }), file, indent=2)

def pillar_recipe_base(filename_parts, inputs, output):
    p = os.path.join('..\\tfc_decoration/recipes', *filename_parts) + '.json'
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as file:
        json.dump(del_none({
            "type": "minecraft:crafting_shaped",
              "pattern": [
                "X",
                "X"
              ],
              "key": {
                "X": {
                  "item": inputs
                }
              },
              "result": {
                "item": output,
                "count": 1
              }
        }), file, indent=2)
def pillar_recipe(filename_parts, stone_type):
    pillar_recipe_base(filename_parts, "tfc:raw/"+stone_type, 'tfc_decoration:pillar/'+stone_type)
def sandstone_pillar_recipe(filename_parts, stone_type):
    pillar_recipe_base(filename_parts, "tfc_decoration:sandstone/"+stone_type, "tfc_decoration:sandstone_pillar/"+stone_type)
def mud_pillar_recipe(filename_parts, stone_type):
    pillar_recipe_base(filename_parts, "tfc_decoration:mud/"+stone_type, "tfc_decoration:mud/"+stone_type)
def chisel_recipe(filename_parts, input, output):
    p = os.path.join('..\\tfc_decoration/recipes', *filename_parts) + '.json'
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as file:
        json.dump(del_none({
            '__comment': 'Generated by generateResources.py function: chisel_recipe',
            'type': 'tfc:damage_item_shapeless',
            "ingredients": [
			{
			  "item": input
			},
			{
			  "type": "forge:ore_dict",
			  "ore": "chisel"
			}
			],
            'result': {
			  'item':output
			},
        }), file, indent=2)

def shapeless_recipe(filename_parts, input, output):
    p = os.path.join('..\\tfc_decoration/recipes', *filename_parts) + '.json'
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as file:
        json.dump(del_none({
            '__comment': 'Generated by generateResources.py function: shapeless_recipe',
            'type': 'minecraft:crafting_shapeless',
            "ingredients": input,
            'result': output
        }), file, indent=2)

def brick_recipe(filename_parts, input, output):
    p = os.path.join('..\\tfc_decoration/recipes', *filename_parts) + '.json'
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as file:
        json.dump(del_none({
            '__comment': 'Generated by generateResources.py function: shaped_recipe',
            'type': 'minecraft:crafting_shaped',
            "pattern": [
                "XOX",
                "OXO",
                "XOX"
            ],
            "key": {
                "O": {
                      "type": "forge:ore_dict",
                      "ore": "mortar"
                    },
                "X": {
                  "item": input
                }
            },
            'result': {
			  'item':output,
			  'count': 4
			},
        }), file, indent=2)
def sandstone_recipe(filename_parts, rock_type) :
    shapeless_recipe(filename_parts, [{'item': 'tfc:sand/'+rock_type}, {'item': 'tfc:sand/'+rock_type}, {'item': 'tfc:sand/'+rock_type}, {'item': 'tfc:sand/'+rock_type}], { 'item':'tfc_decoration:sandstone/'+rock_type })

# ROCK STUFF
for rock_type in ROCK_TYPES:
    # FULL BLOCKS
    for block_type in FULLBLOCK_TYPES:
        if block_type == 'sandstone' :
          cube_bottom_top((block_type, rock_type), ['tfc_decoration:blocks/stonetypes/%s/side/%s' % (block_type, rock_type), 'tfc_decoration:blocks/stonetypes/%s/bottom/%s' % (block_type, rock_type), 'tfc_decoration:blocks/stonetypes/%s/top/%s' % (block_type, rock_type)])
        elif block_type == 'pillar' or block_type == 'sandstone_pillar' or block_type == 'mud_pillar' :
            cube_column((block_type, rock_type), ['tfc_decoration:blocks/stonetypes/%s/normal/%s' % (block_type, rock_type), 'tfc_decoration:blocks/stonetypes/%s/top/%s' % (block_type, rock_type)])
        else :
          cube_all((block_type, rock_type), 'tfc_decoration:blocks/stonetypes/%s/%s' % (block_type, rock_type))

    for item_type in ['mud_ball', 'mud_brick'] :
        item((item_type,rock_type), 'tfc_decoration:items/stonetypes/%s/%s' % (item_type, rock_type))
    
    # recipe
    chisel_recipe(('stone',rock_type, 'cracked_'+rock_type), 'tfc:bricks/'+rock_type, 'tfc_decoration:cracked_bricks/'+rock_type)
    brick_recipe(('stone', rock_type, 'mud_bricks'), 'tfc_decoration:mud_brick/'+rock_type, 'tfc_decoration:mud_bricks/'+rock_type)
    sandstone_recipe(('stone', rock_type, 'sandstone'), rock_type)
    shapeless_recipe(('stone', rock_type, rock_type+'_mud_ball'), [{'item':'tfc:straw'}, {'item':'tfc:dirt/'+rock_type}, {'item':'minecraft:clay'}], { 'item':'tfc_decoration:mud_ball/'+rock_type });
    chisel_recipe(('stone',rock_type, rock_type+'_mud_brick'), 'tfc_decoration:mud_ball/'+rock_type, 'tfc_decoration:mud_brick/'+rock_type)
    pillar_recipe(('stone',rock_type, rock_type+'_pillar'), rock_type)
    sandstone_pillar_recipe(('stone',rock_type, rock_type+'_sandstone_pillar'), rock_type)
    sandstone_pillar_recipe(('stone',rock_type, rock_type+'_mud_pillar'), rock_type)
    shapeless_recipe(('stone',rock_type, rock_type+'_raw_mud'), [{ 'item':'tfc_decoration:raw_mud/'+rock_type }], { 'item':'tfc_decoration:mud_ball/'+rock_type, 'count':4 })

# WOOD STUFF

for wood_type in WOOD_TYPES:
    blockstate(('wood', 'fence_log',wood_type), 'tfc_decoration:wood/fence/fence_post', textures={
        'top':'tfc:blocks/wood/top/%s' % wood_type,
        'log':'tfc:blocks/wood/log/%s' % wood_type,
        'planks':'tfc:blocks/wood/planks/%s' % wood_type,
        'particle':'tfc:blocks/wood/log/%s' % wood_type
    }, variants= {
    "normal": [
      {}
    ],
    "inventory": {
      "model": "tfc_decoration:wood/fence/fence_inventory"
    },
    "north": {
      "true": {
        "submodel": "tfc_decoration:wood/fence/fence_side"
      },
      "false": {}
    },
    "east": {
      "true": {
        "submodel": "tfc_decoration:wood/fence/fence_side",
        "y": 90
      },
      "false": {}
    },
    "south": {
      "true": {
        "submodel": "tfc_decoration:wood/fence/fence_side",
        "y": 180
      },
      "false": {}
    },
    "west": {
      "true": {
        "submodel": "tfc_decoration:wood/fence/fence_side",
        "y": 270
      },
      "false": {}
    }
    })
    shapedRecipe(('wood', wood_type, wood_type+'_fence_log'), wood_type)